import type { Metadata } from "next";
import { Encode_Sans_Condensed } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ClerkUI from "@/components/Clerk";
import { Toaster } from "sonner";
import ThemeToggle from "@/components/ThemeToggle";

const encodeSans = Encode_Sans_Condensed({
  subsets: ["latin"],
  weight: ["300","400","500","600","700"],
  variable: "--font-encode-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${encodeSans.className} antialiased`}>
          <ClerkUI />
          {children}
          <Toaster position="top-right" richColors/>
          <ThemeToggle/>
        </body>
      </html>
    </ClerkProvider>
  );
}
