apiVersion: networking.istio.io/v1beta1
kind: DestinationRule

metadata:
  name: opsentrix-dr-backend
  namespace: opsentrix

spec:
  host: opservice-backend
  trafficPolicy:
    loadBalancer:
      consistentHash:
        useSourceIp: true

    connectionPool:
      tcp:
        maxConnections: 50
      http:
        http1MaxPendingRequests: 30
        http2MaxRequests: 100
        maxRequestsPerConnection: 0  # Unlimited for WebSocket

    outlierDetection:
      consecutive5xxErrors: 5
      interval: 5s
      baseEjectionTime: 30s
      maxEjectionPercent: 50